#server:
 #port: 8081
  #servlet:
    #context-path: /demo
server:
  port: 8081

#测试获取配置文件中字符串
cupSize: F
#测试获取配置文件中获取数字
age: 20
#测试在配置中获取配置属性
content: "cupSize: ${cupSize} age: ${age}"
#测试配置属性获取
gril:
   cupSize: C
   age: 19