#server:
 #port: 8081
  #servlet:
    #context-path: /demo
server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
      #使用Jpa生成数据库字段名称规范驼峰/下划线
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

